# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Let's go Kakao
email:bannono93@naver.com
description: 매일 1시간 이상 코드 공부합시다.
baseurl: "/nsu.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/bannono93/nus.github.io" # the base hostname & protocol for your site
twitter_username: bannono93
github_username:  bannono93

# Build settings
markdown: kramdown
